# Generated by Django 4.1.7 on 2023-05-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
    ]
